apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: ghcr.io/lidandan1/docker/hellow_word:v1
        ports:
        - containerPort: 80
        readinessProbe:
          exec:
            command:
              - "sh"
              - "-c"
              - "ps aux | grep python"  # 检查 Python 进程是否运行
          initialDelaySeconds: 5  # 容器启动后 5 秒开始检查
          periodSeconds: 10  # 每 10 秒检查一次
          timeoutSeconds: 2   # 每次检查的超时时间
        livenessProbe:
          exec:
            command:
              - "sh"
              - "-c"
              - "ps aux | grep python"  # 检查 Python 进程是否运行
          initialDelaySeconds: 10  # 容器启动后 10 秒开始检查
          periodSeconds: 10  # 每 10 秒检查一次
          timeoutSeconds: 2  # 每次检查的超时时间
