apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: ghcr.io/lidandan1/docker/hellow_word:v1
        ports:
        - containerPort: 80
        livenessProbe:
          exec:
            command:
              - "ps"
              - "aux"  # 检查是否有 python 进程在运行
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
              - "ps"
              - "aux"  # 检查是否有 python 进程在运行
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
