apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: ghcr.io/lidandan1/docker/hellow_word:v1
        ports:
        - containerPort: 80
        readinessProbe:
          exec:
            command:
              - "sh"
              - "-c"
              - "ps aux | grep 'echo Hello'"
          initialDelaySeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          exec:
            command:
              - "sh"
              - "-c"
              - "ps aux | grep 'echo Hello'"
          initialDelaySeconds: 5
          timeoutSeconds: 2
