apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: ghcr.io/lidandan1/docker/hellow_word:v1
        ports:
        - containerPort: 80
        livenessProbe:
          exec:
            command:
              - "echo"
              - "health check"
          initialDelaySeconds: 5   # 启动后等待 5 秒进行首次检查
          periodSeconds: 10        # 每 10 秒进行检查一次
          failureThreshold: 3       # 连续 3 次失败认为容器不健康
        readinessProbe:
          exec:
            command:
              - "echo"
              - "readiness check"
          initialDelaySeconds: 5   # 启动后等待 5 秒进行首次检查
          periodSeconds: 10        # 每 10 秒进行检查一次
          failureThreshold: 3       # 连续 3 次失败认为容器未准备好接收流量
